import { type FieldProps } from '../../components/ProfileField/Field/typings';

export const userProfileInputFields: FieldProps[] = [
  {
    title: 'First Name',
    type: 'text',
    id: 'firstName',
    placeholder: 'First Name',
    label: '',
    errorMessage: '',
  },
  {
    title: 'Second Name',
    type: 'text',
    id: 'second_name',
    placeholder: 'Second Name',
    label: '',
    errorMessage: '',
  },
  {
    title: 'Login',
    type: 'text',
    id: 'login',
    placeholder: 'Логин',
    required: true,
    label: 'dsfgsg',
    errorMessage: '',
  },
  {
    title: 'Email',
    type: 'email',
    id: 'email',
    placeholder: 'test@mail.com',
    required: true,
    label: 'dsfgsg',
    errorMessage: '',
  },
  {
    title: 'Game Name',
    type: 'text',
    id: 'display_name',
    placeholder: 'Имя в чате',
    label: 'dsfgsg',
    errorMessage: '',
  },
  {
    title: 'Phone',
    type: 'tel',
    id: 'phone',
    placeholder: 'Телефон',
    label: 'dsfgsg',
    errorMessage: '',
  },
  {
    title: 'Old Password',
    type: 'password',
    id: 'oldPassword',
    placeholder: 'Старый пароль',
    label: 'dsfgsg',
    errorMessage: '',
  },
  {
    title: 'New Password',
    type: 'password',
    id: 'newPassword',
    placeholder: 'Новый пароль',
    label: 'dsfgsg',
    errorMessage: '',
  },
];
