export const inputData = {
  firstName: {
    title: 'First Name',
    inputName: 'first_name',
    placeholder: 'Имя',
    type: 'text',
    pattern: '^[А-ЯЁA-Z]{1,}[а-яёa-z-]+$',
    errorMessage: 'Латиница или кириллица, первая буква заглавня, без пробелов, цифр и спецсимволов (допустим только дефис)',
    required: true,
  },
  secondName: {
    title: 'Second Name',
    inputName: 'second_name',
    placeholder: 'Фамилия',
    type: 'text',
    pattern: '^[А-ЯЁA-Z]{1,}[а-яёa-z-]+$',
    errorMessage: 'Латиница или кириллица, первая буква заглавня, без пробелов, цифр и спецсимволов (допустим только дефис)',
    required: true,
  },
  login: {
    title: 'Login',
    inputName: 'login',
    placeholder: 'Логин',
    type: 'text',
    pattern: '^(?=.*[a-zA-Z])[a-zA-Z0-9_-]+$',
    errorMessage: 'Латиница, может содержать цифры, но не состоять из них, (допустимы дефис и нижнее подчёркивание)',
    minLength: 3,
    maxLength: 20,
    required: true,
  },
  email: {
    title: 'E-mail',
    inputName: 'email',
    placeholder: 'E-mail',
    type: 'e-mail',
    pattern: '^[-\\w.]+@([A-z0-9][-A-z0-9]+\\.)+[A-z]{2,4}$',
    errorMessage: 'Латиница, может включать цифры и спецсимволы вроде дефиса, обязательно должна быть «собака»',
    required: true,
  },
  password: {
    title: 'Password',
    inputName: 'password',
    placeholder: 'Пароль',
    type: 'password',
    pattern: '^(?=.*[0-9])(?=.*[А-ЯЁA-Z])[а-яА-ЯёЁa-zA-Z0-9]+$',
    errorMessage: 'Обязательно хотя бы одна заглавная буква и цифра',
    minLength: 8,
    maxLength: 40,
    required: true,
  },
  displayName: {
    title: 'Display Name',
    inputName: 'display_name',
    placeholder: 'Никнейм',
    type: 'text',
    errorMessage: '',
  },
  phone: {
    title: 'Phone',
    inputName: 'phone',
    placeholder: 'Телефон',
    type: 'phone',
    pattern: '^(\\+7)?[0-9]{10,13}$',
    errorMessage: 'От 10 до 13 символов, состоит из цифр, может начинаться с +7',
    required: true,
  },
};
